import torch
ckpt = torch.load("workspace/03_CHECKPOINTS_1.7B_SMOL_DENSE_V1/organism_cycle_000.pt", map_location="cpu", weights_only=False, mmap=True)
config = ckpt["config"]
print("=== DARWIN-X ARCHITECTURE ===")
print(f"  feed_forward_kind: {config.get('feed_forward_kind')}")
print(f"  ssd_attention_ratio: {config.get('ssd_attention_ratio')}")
print(f"  d_model: {config.get('d_model')}")
print(f"  n_layers: {config.get('n_layers')}")
print(f"  rope_style: {config.get('rope_style')}")
print(f"  qkv_bias: {config.get('qkv_bias')}")
print()
print("=== DONOR (SmolLM2-1.7B) ===")
print("  Standard LlamaAttention (MHA)")
print("  LlamaMLP (SwiGLU)")
print("  RMSNorm")
print()
print("=== RECIPIENT (DarwinX) ===")
print(f"  Mixed SSD/MHA ({config.get('ssd_attention_ratio')} ratio)")
print(f"  DenseSwiGLU (custom implementation)")
print(f"  RMSNorm (custom implementation)")
print()
print("=== ROOT CAUSE ===")
print("  KL=0.62 even with ALL organs disabled.")
print("  NOT spider_sense. NOT inter_hemispheric. NOT GABA.")
print("  The computation graph is DIFFERENT:")
print("  - SSD layers replace some attention layers")
print("  - DenseSwiGLU replaces LlamaMLP")
print("  - Custom norm implementations")
print("  Same weights, different graph = different function.")
print("  This is the fundamental limit of architecture transplant.")
